# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    puts(“ Starting the build”)
    
  end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
lane :custom_lane do |options|
  xcodebuild(
    workspace: "FastLaneTestUpdated.xcworkspace",
    scheme: "FastLaneTestUpdated",
    configuration: "Debug",
    clean: options[:clean],
    build: true,
    destination: "generic/platform=iOS",
    build_settings: {
      "CODE_SIGNING_REQUIRED" => "NO",
      "CODE_SIGN_IDENTITY" => ""
    }
  )
end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
	puts(“ Hello Fastlane has finished your build”)
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
	puts(“ Hello Fastlane has found error in your build”)
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
